name: Alpine-Linux

on:
    workflow_dispatch:
        branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: jirutka/setup-alpine@v1
        with:
          branch: v3.15
          packages: >
            tcl
            tk
            git
            R
            R-dev
            python3
            make
            xvfb-run
      - run: |
          cat /etc/alpine-release
          ls -l
          echo "parray tcl_platform" | tclsh
          echo "puts [set tcl_patchLevel]" | tclsh
          Rscript --version
          python3 --version
          pwd
          xvvb-run :99 -ac -screen 0 1024x768x8 & 
          export DISPLAY=":99"
          mkdir R
          Rscript -e 'install.packages("MASS",repos="http://cran.us.r-project.org",lib="R");'
          git clone https://github.com/mittelmark/pantcl4r.git
          cd pantcl4r
          export R_LIBS=`pwd`/../R
          ls -l ../R
          export _R_CHECK_FORCE_SUGGESTS_=0
          R CMD build --no-build-vignettes --no-manual .
          R CMD check --no-build-vignettes --no-manual .
        shell: alpine.sh {0}
