name: Alpine-Linux

on:
    workflow_dispatch:
        branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: jirutka/setup-alpine@v1
        with:
          branch: v3.18
          packages: >
            tcl
            tk
            git
            R
            python3
            make
      - run: |
          cat /etc/alpine-release
          ls -l
          echo "parray tcl_platform" | tclsh
          echo "puts [set tcl_patchLevel]" | tclsh
          Rscript --version
          python --version
          pwd
          mkdir R
          Rscript -e 'install.packages(c("knitr","rmarkdown"),repos="http://cran.us.r-project.org",lib="R");'
          git clone https://github.com/mittelmark/snha.git
          cd snha
          export R_LIBS=`pwd`/../R
          ls -l ../R
          make build
          make check
        shell: alpine.sh {0}
