name: Alpine-Linux

on:
    workflow_dispatch:
        branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: jirutka/setup-alpine@v1
        with:
          branch: v3.18
          packages: >
            tcl
            tk
            git
            R
            python3
      - run: |
          cat /etc/alpine-release
          ls -l
          echo "parray tcl_platform" | tclsh
          echo "puts [set tcl_patchLevel]" | tclsh
          Rscript --version
        shell: alpine.sh {0}
