name: Makefile Package

on:
  workflow_dispatch:
    branches: [ master ]
env:
   VERSION: "0.3.0"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:       
    - uses: actions/checkout@v4
    - name: Build
      run: |
        sudo apt-get install texlive-base
        Rscript -e 'install.packages("https://github.com/mittelmark/pantcl4r/releases/download/v0.3.0/pantcl4r_0.3.0.tar.gz", repos=NULL);'
        make build
        make check
        make install
        cp snha_0.3.0.tar.gz build/
    - name: Upload Artifact GitHub Action
      uses: actions/upload-artifact@v4
      with: 
         name: snha_0.3.0.tar.gz
         path: build/snha_0.3.0.tar.gz

