name: Makefile Package

on:
  workflow_dispatch:
    branches: [ master ]
env:
   VERSION: "0.3.0"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:       
    - uses: actions/checkout@v4
    - name: Build
      run: |
        export DISPLAY=:99.0
        sudo apt-get install texlive-full
        mkdir ~/R
        Rscript -e '.libPaths(c("~/R",.libPaths()));install.packages("https://github.com/mittelmark/pantcl4r/releases/download/v0.3.0/pantcl4r_0.3.0.tar.gz", repos=NULL);'
        echo '.libPaths(c("~/R",.libPaths()))' > ~/.Rprofile
        make build
        make check
        make install
        mkdir build
        cp pantcl4r_0.3.0.tar.gz build/
    - name: Upload Artifact GitHub Action
      uses: actions/upload-artifact@v4
      with: 
         name: pantcl4r_0.3.0.tar.gz
         path: build/pantcl4r_0.3.0.tar.gz

